Repository qor5/x, pull requests merged in 2024-07, with the labels that each got.

#201 modify selectedIds handling of datatable
  ui/vuetifyx/data-table.go
Labels: size/L

#203 add colors;load can scroll;inner virtual can options
  ui/vuetify/fix-color-theme.go
  ui/vuetify/vuetifyjs/dist/index.js
  ui/vuetify/vuetifyjs/src/plugins/theme.js
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/L

#202 Upgrade to Vuetify v3.6.11
  ui/vuetify/build.sh
  ui/vuetify/dist/vuetify.min.css
  ui/vuetify/dist/vuetify.min.js
  ui/vuetify/vuetifyjs/dist/index.js
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/package.json
  ui/vuetify/vuetifyjs/pnpm-lock.yaml
Labels: size/XXL

#204 avoid render error when given undefined select option
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/M

#206 Fix i18n-transfer import BUG
  i18n/i18n-transfer/parser/export_to_translation_map.go
  i18n/i18n-transfer/parser/import_from_translation_map.go
  i18n/i18n-transfer/test/mock/test_import.csv
  i18n/i18n-transfer/test/transfer_test.go
Labels: size/L

#208 add vxoverlay;add vx go file
  ui/vuetifyx/draggable.go
  ui/vuetifyx/overlay.go
  ui/vuetifyx/scroll-iframe.go
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/public/iframe.html
  ui/vuetifyx/vuetifyxjs/src/demo/App.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/OverlayExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Overlay.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
  ui/vuetifyx/vuetifyxjs/src/lib/main.ts
Labels: size/XL

#209 add LanguageTagFromContext
  i18n/i18n.go
  i18n/i18n_test.go
Labels: size/S

#210 upgrade cropper
  ui/cropper/cropperjs/package.json
  ui/cropper/cropperjs/pnpm-lock.yaml
  ui/cropper/cropperjs/src/demo/components/CropperExample.vue
  ui/cropper/cropperjs/src/lib/Cropper.vue
Labels: size/M

#211 build
  ui/cropper/cropperjs/dist/cropperjs.css
  ui/cropper/cropperjs/dist/cropperjs.umd.cjs
Labels: size/S

#212 datepicker: emptyable clear text
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
Labels: size/S

#213 move new cropper to loaded
  ui/cropper/cropperjs/dist/cropperjs.umd.cjs
  ui/cropper/cropperjs/src/lib/Cropper.vue
Labels: size/S

#214 Feat: i18n export support embed out package struct
  i18n/i18n-transfer/README.md
  i18n/i18n-transfer/parser/export_to_translation_map.go
  i18n/i18n-transfer/test/mock/messages/message.go
  i18n/i18n-transfer/test/mock/out_messages/message.go
Labels: size/M

#215 datepicker: model value will not be updated until selection is confirmed
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
Labels: size/S

#216 datepicker: ensure set model value every dialog visible
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
Labels: size/M

#217 fix autocomplete
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
Labels: size/XXL

#218 fix: theme config is not working
  ui/vuetify/vuetifyjs/src/plugins/theme.js
Labels: size/L

#219 fix auto complete updatemodel
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
Labels: size/XS

#220 datepicker: make datePickerProps available
  ui/vuetifyx/datetime-picker.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/demo/components/DatepickerExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/DatetimepickerExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
Labels: size/XXL

#222 fix: menu content can not scroll when content is overflow
  ui/vuetify/vuetifyjs/src/scss/components/_Menu.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/S

#223 fix: rollback theme.js
  ui/cropper/cropperjs/package.json
  ui/cropper/cropperjs/pnpm-lock.yaml
  ui/redactor/redactorjs/package.json
  ui/redactor/redactorjs/pnpm-lock.yaml
  ui/vuetify/vuetifyjs/package.json
  ui/vuetify/vuetifyjs/pnpm-lock.yaml
  ui/vuetify/vuetifyjs/src/plugins/theme.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/XXL
