Repository qor5/x, pull requests merged in 2024-10, with the labels that each got.

#308 Feat UI reborn
  ui/vuetifyx/text-field.go
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vx-dialog.go
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-select.go
Labels: size/L

#309 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Drawer.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Section.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/L

#310 feat: vx-checkbox logic optimization and add docs
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXCheckbox/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXCheckbox.vue
  ui/vuetifyx/vx-checkbox.go
Labels: size/L

#311 tagbuilder add SetAttr func
  ui/vuetifyx/tiptap-editor.go
  ui/vuetifyx/vx-dialog.go
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-label.go
  ui/vuetifyx/vx-select.go
  ui/vuetifyx/vx-toolbar.go
Labels: size/M

#312 perm: idempotence createPolicy
  perm/builder.go
Labels: size/XS

#313 feat: add support of password, optimize logic of vx-field and doc, ad…
  ui/vuetifyx/vuetifyxjs/docs/Components/VXCheckbox/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXCheckbox.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useBindingValue.ts
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-label.go
  ui/vuetifyx/vx-select.go
Labels: size/XL

#314 upgrade web to v3.0.10
  go.mod
  go.sum
Labels: size/S

#318 feat：add vx-avatar and docs
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/config.ts
  ui/vuetifyx/vuetifyxjs/docs/Components/VXAvatar/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXLabel/index.md
  ui/vuetifyx/vuetifyxjs/docs/public/imgs/vx-avatar-example.png
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/VXAvatar.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-avatar.go
  ui/vuetifyx/vx-label.go
Labels: size/L

#320 fix: adjust the wrong path of scripts creates
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/scripts/new-demo-doc.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
Labels: size/M

#322 style: change the password eye icon
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
Labels: size/XS

#325 vx field add Clearable
  ui/vuetifyx/tiptap-editor.go
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vx-dialog.go
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-label.go
  ui/vuetifyx/vx-select.go
  ui/vuetifyx/vx-toolbar.go
Labels: size/S

#324 feat: add base datepicker and datetimepicker
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/DatePicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/scripts/new-demo-doc.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePickerBase.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimeSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useBindingValue.ts
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useVDatePicker.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/i18n.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
Labels: size/XXL

#326 fix: fix lodash imported as a esmodule
  ui/vuetifyx/date-picker.go
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePickerBase.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
  ui/vuetifyx/vx-date-picker.go
  ui/vuetifyx/vx-range-picker.go
Labels: size/XL

#327 docs: fix dead link
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
Labels: size/L

#328 fix VXRangePicker Placeholder; VXDialogBuilder add Height
  ui/vuetifyx/vx-dialog.go
  ui/vuetifyx/vx-range-picker.go
Labels: size/XS

#331 fix: v-number-input slot have default empty placeholder
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
Labels: size/M
