Repository qor5/x, pull requests merged in 2024-11, with the labels that each got.

#335 fix: vx-field event trigger twice
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useFilteredAttrs.ts
Labels: size/S

#336 feat: add comp of vx-pagination
  ui/vuetifyx/vuetifyxjs/docs/Components/VXPagination/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXPagination.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-pagination.go
Labels: size/L

#333 add i18n labels for datarange filters
  ui/vuetifyx/filter.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DateRangeItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DatetimeRangeItem.vue
Labels: size/S

#337 add vx-tabs & fix ranger-picker icon click area
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/docs/Components/VXPagination/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXTabs/index.md
  ui/vuetifyx/vuetifyxjs/docs/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/mocks/autocomplete.json
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Tabs/VXTabs.vue
  ui/vuetifyx/vuetifyxjs/src/lib/VXAvatar.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useFilteredAttrs.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_SlideGroup.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VTable.scss
  ui/vuetifyx/vx-tabs.go
Labels: size/XL

#340 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXCheckbox/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXCheckbox.vue
  ui/vuetifyx/vuetifyxjs/src/lib/icons/checkbox-filled-outline.vue
  ui/vuetifyx/vuetifyxjs/src/lib/icons/checkbox-on-filled-outline.vue
Labels: size/L

#341 fix: remove detailing page vtabs underline effect for vx-tabs
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/XS

#339 font-weight 510 => 500 && upgrade jwt dep to v4.5.1
  go.mod
  go.sum
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_vuetify.scss
Labels: size/S

#342 login err500
  login/builder.go
  ui/tiptap/build.sh
Labels: size/XS

#347 migrate oss to x and use aws sdk v2
  go.mod
  go.sum
  oss/.gitignore
  oss/aliyun/README.md
  oss/aliyun/aliyun.go
  oss/aliyun/aliyun_test.go
  oss/filesystem/filesystem.go
  oss/filesystem/filesystem_test.go
  oss/oss.go
  oss/qiniu/README.md
  oss/qiniu/qiniu.go
  oss/qiniu/qiniu_test.go
  oss/s3/README.md
  oss/s3/s3.go
  oss/s3/s3_test.go
  oss/tencent/tencent.go
  oss/tencent/tencent_test.go
  oss/tencent/util.go
  oss/tests/sample.txt
  oss/tests/tests.go
Labels: size/XXL

#356 Ci daniel autobuild
  .github/workflows/go.yml
  .github/workflows/vuetifyjs-test.yml
  ui/vuetifyx/vuetifyxjs/.gitignore
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
Labels: size/M

#354 Ci daniel autobuild
  .github/workflows/go.yml
  .github/workflows/vuetifyjs-build.yml
  .github/workflows/vuetifyjs-test.yml
  ui/vuetifyx/vuetifyxjs/.gitignore
Labels: size/M

#358 Ci daniel autobuild
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtn/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
Labels: size/XL

#357 feat: add vx-btn
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtn/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
Labels: size/XL

#359 feat: support go hooks of vx-btn
  ui/vuetifyx/vx-btn.go
Labels: size/L

#360 remove set container style height
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/XS
