Repository qor5/x, pull requests merged in 2024-08, with the labels that each got.

#224 Upgrade new released web v3.0.5
  go.mod
  go.sum
Labels: size/L

#225 style:UI improvement of listingComp new btn、title-bar and mapping scss vars from vuetify theme.js vars
  ui/vuetify/vuetifyjs/dist/index.js
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_variables.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Layout.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Listing.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VBtn.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
  ui/vuetify/vuetifyjs/src/scss/utils.scss
Labels: size/M

#226 style: fix continuous characters word break problem and filter comp a…
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_fixer.scss
  ui/vuetify/vuetifyjs/src/scss/components/_SlideGroup.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VBtn.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
  ui/vuetify/vuetifyjs/src/scss/utils.scss
Labels: size/M

#227 update translations
  login/messages.go
Labels: size/S

#228 Feat UI reborn
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_fixer.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Menu.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Navigation.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/L

#229 style：navigator ui improvement( profile bar and folding effect optimise)
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_fixer.scss
  ui/vuetify/vuetifyjs/src/scss/_utils.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Navigation.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/M

#230 Feat UI reborn
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_fixer.scss
  ui/vuetify/vuetifyjs/src/scss/_utils.scss
  ui/vuetify/vuetifyjs/src/scss/_variables.scss
  ui/vuetify/vuetifyjs/src/scss/_vuetify.scss
  ui/vuetify/vuetifyjs/src/scss/components/_AutoComplete.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Dialog.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Input.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Navigation.scss
  ui/vuetify/vuetifyjs/src/scss/components/_SlideGroup.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VBtn.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VCard.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VTable.scss
  ui/vuetify/vuetifyjs/src/scss/components/_vTabs.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/L

#233 VXTablePagination: use v.VPagination
  ui/vuetifyx/table-pagination.go
Labels: size/M

#232 fix: fix the unexpected influence of menu style adjusting to page builder.
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/components/_Navigation.scss
Labels: size/M

#234 upgrade autocomplete
  ui/vuetifyx/autocomplete-fix.go
  ui/vuetifyx/autocomplete.go
  ui/vuetifyx/scroll-iframe.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/mocks/autocomplete.json
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/demo/components/AutoCompleteExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/FilterExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/Model.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/SelectItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
  ui/vuetifyx/vuetifyxjs/src/lib/__tests__/Autocomplete.spec.ts
  ui/vuetifyx/vuetifyxjs/src/lib/__tests__/handler.ts
  ui/vuetifyx/vuetifyxjs/tsconfig.json
Labels: size/XXL

#235 cropper container add height,witdh where image load
  ui/cropper/cropperjs/dist/cropperjs.umd.cjs
  ui/cropper/cropperjs/pnpm-lock.yaml
  ui/cropper/cropperjs/src/lib/Cropper.vue
Labels: size/XXL

#236 fix overlay top view
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/lib/Overlay.vue
Labels: size/XS

#239 add textarea-with-bottom-btns
  ui/vuetify/dist/vuetify.min.css
  ui/vuetify/dist/vuetify.min.js
  ui/vuetify/vuetifyjs/components.d.ts
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_utils.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VTextarea.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/XXL

#240 Feat UI reborn
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/_vuetify.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Detailing.scss
  ui/vuetify/vuetifyjs/src/scss/components/_Navigation.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
  ui/vuetify/vuetifyjs/src/scss/sites/k-theme.scss
Labels: size/L

#241 login: set auth cookie default SameSite config to Lax
  login/builder.go
Labels: size/XS

#242 pagination: temporary fix for jitter issues
  ui/vuetifyx/table-pagination.go
Labels: size/S

#243 Feat UI reborn
  ui/vuetify/vuetifyjs/dist/vuetify/assets/index.css
  ui/vuetify/vuetifyjs/src/scss/components/_Detailing.scss
  ui/vuetify/vuetifyjs/src/scss/components/_VPagination.scss
  ui/vuetify/vuetifyjs/src/scss/index.scss
Labels: size/S

#244 login: add wrap hook methods && add beforeTOTPFlowHook
  login/builder.go
  login/middleware.go
Labels: size/L

#247 login: ErrorPasswordNotMatch i18n
  login/messages.go
Labels: size/XS

#248 web/v3 3.0.6
  go.mod
  go.sum
Labels: size/S

#249 vtable add hover
  ui/vuetifyx/data-table.go
Labels: size/S

#250 add vue-i18n && improve datepicker ui
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/demo/App.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/Autocomplete.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/Card.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/Checkbox.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/Table.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/TextField.vue
  ui/vuetifyx/vuetifyxjs/src/demo/plugins/i18n.ts
  ui/vuetifyx/vuetifyxjs/src/demo/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/demo/plugins/vuetify.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/i18n.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/theme.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/vuetify.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_mixins.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_utils.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_variables.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_vuetify.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_AutoComplete.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Input.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Listing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Navigation.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_SlideGroup.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VBtn.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VCard.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VPagination.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VTable.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VTextarea.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_vTabs.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/sites/k-theme.scss
Labels: size/XXL

#251 Update ui/vuetify to v3.6.14
  ui/vuetify/calendar.go
  ui/vuetify/data-table-server.go
  ui/vuetify/data-table.go
  ui/vuetify/date-input.go
  ui/vuetify/date-picker-controls.go
  ui/vuetify/date-picker-month.go
  ui/vuetify/date-picker.go
  ui/vuetify/expansion-panels.go
  ui/vuetify/fab.go
  ui/vuetify/gen_vuetify.sh
  ui/vuetify/number-input.go
  ui/vuetify/stepper-vertical.go
  ui/vuetify/time-picker-controls.go
Labels: size/L

#252 style: kak detailing page amount detail section
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Detailing.scss
Labels: size/S

#255 fix linkage selectOutOfOrder
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/demo/components/FilterExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/LinkageSelectExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Detailing.scss
Labels: size/XXL

#256 fix autocomplete search null;adjust pagination size
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
Labels: size/XS

#257 tweak filter wrap input
  ui/vuetifyx/filter.go
Labels: size/M

#258 style: confirm dialog adjusting
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
Labels: size/S

#259 style: adjusting of filter area layout
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButton.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Detailing.scss
Labels: size/M

#260 fix: https://theplanttokyo.atlassian.net/browse/KAK-3728
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/i18n.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Drawer.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Listing.scss
Labels: size/XXL

#261 login: add GenerateResetPasswordTokenExpiration for UserPass
  .gitignore
  login/user_pass.go
Labels: size/S

#262 style: add the missing class
  ui/vuetifyx/table-pagination.go
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Layout.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VPagination.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/S

#263 style: fix the padding of version-list dialog
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/M

#264 upgrade web/v3 to v3.0.7
  go.mod
  go.sum
Labels: size/XS

#265 style: fix https://theplanttokyo.atlassian.net/browse/KAK-3155
  ui/vuetifyx/readonly-field.go
Labels: size/XS

#266 style: https://theplanttokyo.atlassian.net/browse/KAK-3020
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
Labels: size/XS
