Repository qor5/x, pull requests merged in 2024-09, with the labels that each got.

#267 datepicker: fix DialogWidth param type
  ui/vuetifyx/date-picker.go
  ui/vuetifyx/datetime-picker.go
Labels: size/XS

#268 add LinkageSelectRemote;AutoComplete support Object Value
  ui/vuetifyx/autocomplete-fix.go
  ui/vuetifyx/filter.go
  ui/vuetifyx/linkage-select-remote-fix.go
  ui/vuetifyx/linkage-select-remote.go
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/demo/App.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/FilterExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/LinkageSelectRemoteExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/FilterData.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/Model.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/LinkageSelectItemRemote.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/components/LinkSelectAutoComplete.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/main.ts
Labels: size/XXL

#269 fix empty is selected
  ui/vuetifyx/filter.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
Labels: size/S

#271 fix filter empty
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/demo/components/FilterExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/LinkageSelectRemoteExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Autocomplete.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/FilterData.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/Model.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/ItemFilter.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/LinkageSelectItemRemote.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/components/LinkSelectAutoComplete.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Listing.scss
Labels: size/L

#272 filter add date options
  ui/vuetifyx/filter.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/Model.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DateItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DateRangeItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DatetimeRangeItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/TextFiled.vue
  ui/vuetifyx/vuetifyxjs/src/lib/main.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_ActivityTimeLine.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_Dialog.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VField.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VFilter.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VPagination.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VVersionSelect.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_vChip.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Listing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
Labels: size/L

#273 filter: datepicker clear/ok button translation
  ui/vuetifyx/filter.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DateItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DateRangeItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/DatetimeRangeItem.vue
Labels: size/S

#274 fix clear current value next all level parent set empty
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
Labels: size/S

#275 Fix linkage select
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
Labels: size/XS

#276 fix: add min-width of filter comp
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/StringItem.vue
Labels: size/XS

#279 datatable: add ScriptDataTableSwitchSelectedIds
  ui/vuetifyx/data-table.go
Labels: size/S

#280 filter: reset value when menu is opened
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/ItemFilter.vue
Labels: size/M

#278 tiptap
  .gitignore
  go.mod
  ui/vuetifyx/tiptap-editor.go
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/TiptapEditor/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/CallbackActionButton.ts
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/CallbackActionButton.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/ImageGlue.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/TiptapEditor.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/tiptap.ts
Labels: size/XXL

#282 datatable: use watch to handle selected ids changed
  ui/vuetifyx/data-table.go
Labels: size/M

#281 datepicker: add ErrorMessages for datepicker
  ui/vuetifyx/date-picker.go
  ui/vuetifyx/datetime-picker.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
Labels: size/S

#283 web/v3 v3.0.8
  go.mod
  go.sum
Labels: size/S

#284 Feat UI reborn
  .github/workflows/doc-build.yml
  ui/vuetifyx/select-fix.go
  ui/vuetifyx/select.go
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/config.ts
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/theme/theme-default/custom.scss
  ui/vuetifyx/vuetifyxjs/docs/Components/Card/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/Checkbox/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/Select/SelectMany.md
  ui/vuetifyx/vuetifyxjs/docs/Components/Table/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/TextField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/sendVariables.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXLabel/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXToolbar/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXToolBar.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/TextFiled.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useFilteredAttrs.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_utils.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_ActivityTimeLine.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_SlideGroup.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_imgUploader.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_vChip.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/index.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/vite.config.ts.timestamp-1726136066179-be6657ece8be6.mjs
  ui/vuetifyx/vuetifyxjs/vite.config.ts.timestamp-1726195147505-23e259c31dded.mjs
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-label.go
  ui/vuetifyx/vx-select.go
  ui/vuetifyx/vx-toolbar.go
Labels: size/XXL

#286 chore: adjusting of app config
  .gitignore
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/sites/k-theme.scss
  ui/vuetifyx/vuetifyxjs/vite.config.ts.timestamp-1726136066179-be6657ece8be6.mjs
  ui/vuetifyx/vuetifyxjs/vite.config.ts.timestamp-1726195147505-23e259c31dded.mjs
Labels: size/L

#287 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/config.ts
  ui/vuetifyx/vuetifyxjs/docs/Components/Button/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/docs/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/sites/k-theme.scss
  ui/vuetifyx/vx-field.go
  ui/vuetifyx/vx-select.go
Labels: size/L

#289 re add linkage remote;format
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXToolBar.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/ItemFilter.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/CallbackActionButton.ts
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/CallbackActionButton.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/ImageGlue.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/TiptapEditor.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useFilteredAttrs.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/tiptap.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_utils.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_ActivityTimeLine.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_imgUploader.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_vChip.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/sites/k-theme.scss
Labels: size/XL

#290 fix linkage select assign no level label
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelect.vue
Labels: size/XS

#288 style: style adjusting of gap
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/theme/theme-default/styles/components/vp-doc.css
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/scripts/new-demo-doc.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useEventListener.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VTable.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/sites/k-theme.scss
  ui/vuetifyx/vx-dialog.go
Labels: size/XXL

#291 fix(style): fix the problem of wrong conflict resolving.
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/theme/theme-default/components/VPDoc.vue
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/theme/theme-default/custom.scss
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
  ui/vuetifyx/vx-dialog.go
Labels: size/XL

#292 fix: make the sendVariables works with vx-field and discard clear e…
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/sendVariables.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/SendVariables.vue
Labels: size/M

#293 fix: sendVariables
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/sendVariables.md
  ui/vuetifyx/vuetifyxjs/src/lib/SendVariables.vue
Labels: size/S

#294 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/SendVariables.vue
Labels: size/XS

#296 fix Date option Type
  ui/vuetifyx/filter.go
Labels: size/XS

#295 fix: add compatibility to vx-field for sendVariables comp
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/FilterButtonBody.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/SendVariables.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/forwardRefs.ts
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useFilteredAttrs.ts
  ui/vuetifyx/vuetifyxjs/vite.config.ts
Labels: size/L

#297 fix: the latest output code of vuetifyx
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/composables/forwardRefs.ts
Labels: size/M

#298 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/.vitepress/config.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Datepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Datetimepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TextDatepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/forwardRefs.ts
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useVDatePicker.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
Labels: size/L

#299 fix assign after onMounted nextTick
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/SendVariables.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TextDatepicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/components/_VTable.scss
Labels: size/M

#300 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vx-field.go
Labels: size/M

#301 Feat UI reborn
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXLabel.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vx-dialog.go
  ui/vuetifyx/vx-field.go
Labels: size/L

#302 fix: https://theplanttokyo.atlassian.net/browse/KAK-6057
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
Labels: size/XS

#303 chore: change vxfield autoFocus api to autofocus
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vx-field.go
Labels: size/S

#304 VXCheckbox
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXCheckbox/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXCheckbox.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-checkbox.go
Labels: size/XL

#305 upgrade web to v3.0.9
  go.mod
  go.sum
Labels: size/XS

#306 feat: https://theplanttokyo.atlassian.net/browse/KAK-4370?focusedComm…
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
Labels: size/S

#307 feat: support draggable to pagebuilder drawer
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
Labels: size/M
