Repository qor5/x, pull requests merged in 2024-12, with the labels that each got.

#364 Ci daniel autobuild
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtn/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtnGroup/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChip/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtnGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXChip.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useColor.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-btn-group.go
  ui/vuetifyx/vx-btn.go
  ui/vuetifyx/vx-chip.go
Labels: size/XXL

#366 Feat datepicker format
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePickerBase.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimeSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
Labels: size/L

#363 vx-chip(badge)
  .github/workflows/vuetifyjs-build.yml
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtn/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBtnGroup/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChip/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtnGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXChip.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useColor.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-btn-group.go
  ui/vuetifyx/vx-chip.go
Labels: size/XXL

#371 Fix scroll iframe
  ui/vuetifyx/scroll-iframe.go
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/L

#372 changepassword i18n
  login/messages.go
Labels: size/S

#361 login: add ErrShouldNotExtend to support token rotation grace period
  go.mod
  go.sum
  login/middleware.go
Labels: size/M

#377 remove adjust empty
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
Labels: size/L

#380 fix empty body with set iframe disaply
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/XS

#373 feat: support pagebuilder style
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
Labels: size/M

#382 add preload image
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/L

#383 WIP: fix: media style in section has large gap
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/S, do-not-merge/work-in-progress

#388 fix: the format value is not the same sometimes
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
Labels: size/M

#365 feat: support default formatted modelValue and timeSelect functional …
  ui/vuetifyx/scroll-iframe.go
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePickerBase.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimeSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/LinkageSelectRemote/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
Labels: size/L

#391 Fix scrolliframe background
  go.mod
  go.sum
  ui/redactor/redactorjs/pnpm-lock.yaml
  ui/tiptap/tiptapjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/M

#392 fix: Refactor VXBtn and VXChip components for improved attribute hand…
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vx-btn-group.go
  ui/vuetifyx/vx-btn.go
  ui/vuetifyx/vx-chip.go
Labels: size/L

#397 fix: Update VXChipBuilder Color method to accept interface and use JS…
  ui/vuetifyx/vx-chip.go
Labels: size/XS
