Repository qor5/x, pull requests merged in 2024-06, with the labels that each got.

#190 Update the dependent qor5/web to v3.0.4
  go.mod
  go.sum
Labels: size/S

#191 use js default theme
  ui/vuetify/fix-vuetifyjs.go
  ui/vuetify/vuetifyjs/dist/index.js
  ui/vuetify/vuetifyjs/pnpm-lock.yaml
  ui/vuetify/vuetifyjs/src/plugins/theme.js
  ui/vuetify/vuetifyjs/src/plugins/vuetify.js
Labels: size/XXL

#192 scroll-iframe add virtual element
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/demo/App.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/DragListenerExample.vue
  ui/vuetifyx/vuetifyxjs/src/demo/components/ScrollIframeExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/DragListener.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
  ui/vuetifyx/vuetifyxjs/src/lib/main.ts
Labels: size/XXL

#194 fix filter can`t disable choose modifier;filter add warpInput;
  ui/vuetifyx/filter.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/src/demo/components/FilterExample.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/Model.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/MultipleSelectItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Filter/components/StringItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/M

#195 Fix Use qor5 instead of goplaid in i18n-transfer README.md
  i18n/i18n-transfer/README.md
  ui/vuetifyx/readonly-field.go
Labels: size/XS

#197 add cookieConfig Secure
  login/builder.go
Labels: size/S

#198 fix all secure config
  login/builder.go
  login/flash.go
  login/view_helper.go
Labels: size/M

#199 Update deps
  ui/tiptap/tiptapjs/dist/tiptapjs.umd.cjs
  ui/tiptap/tiptapjs/package.json
  ui/tiptap/tiptapjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/dist/vuetifyxjs.umd.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/XXL
