Repository qor5/x, pull requests merged in 2025-03, with the labels that each got.

#408 feat: add vx-breadcrumbs
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBreadcrumbs/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXTreeview/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Breadcrumbs/VXBreadcrumbs.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Treeview/VXTreeview.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-breadcrumbs.go
  ui/vuetifyx/vx-treeview.go
Labels: size/XXL

#426 feat: implement VXSegmentForm component
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSegmentForm/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/ConditionSwitch.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItemGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/index.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/type.d.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/useUtils.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-segment-form.go
Labels: size/XXL

#428 Fix problem by code scan
  login/builder.go
  ui/cropper/cropperjs/dist/cropperjs.umd.cjs
  ui/cropper/cropperjs/package.json
  ui/cropper/cropperjs/pnpm-lock.yaml
  ui/redactor/redactorjs/package.json
  ui/redactor/redactorjs/pnpm-lock.yaml
  ui/tiptap/tiptapjs/dist/tiptap.css
  ui/tiptap/tiptapjs/dist/tiptapjs.umd.cjs
  ui/tiptap/tiptapjs/package.json
  ui/tiptap/tiptapjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/XXL

#431 Feat daniel segment
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItemGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/index.vue
Labels: size/S

#434 remove old datepicker datetimepicker go code
  ui/vuetifyx/date-picker.go
  ui/vuetifyx/datetime-picker.go
Labels: size/L

#424 WIP: Feat daniel chart
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChart/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/VXChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/presets.config.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_vuetify.scss
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
  ui/vuetifyx/vx-chart.go
  ui/vuetifyx/vx-dialog.go
Labels: do-not-merge/work-in-progress, size/XXL

#437 Refactor lodash import in SegmentItem.vue to use named import for debounce
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItem.vue
Labels: size/L

#440 Refactor completeUserAuthCallback to use html/template for secure URL
  go.mod
  go.sum
  login/builder.go
Labels: size/L

#435 Feat style image with text
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/XL

#442 fix: qor5-942
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
Labels: size/S
