Repository qor5/x, pull requests merged in 2025-05, with the labels that each got.

#461 fix: qor5-1121
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItemGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/index.vue
Labels: size/L

#462 fix: QOR5-1088
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/IframeEmailEditor.vue
  ui/vuetifyx/vuetifyxjs/src/lib/IframeEmitter.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-iframe-email-editor.go
  ui/vuetifyx/vx-iframe-emitter.go
Labels: size/L

#460 [Snyk] Upgrade vue-i18n from 9.14.3 to 9.14.4
  ui/vuetifyx/vuetifyxjs/package.json
Labels: size/XS

#466 Feat-vxchart-callback
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChart/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/FunnelChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/VXChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/useVxChartMergeOpts.ts
  ui/vuetifyx/vx-chart.go
Labels: size/L

#468 Support segment-form read only
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSegmentForm/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/ConditionSwitch.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItem.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/SegmentItemGroup.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/index.vue
  ui/vuetifyx/vx-segment-form.go
Labels: size/L

#467 feat: update TiptapEditor with new HtmlView extension and enhance documentation
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/TiptapEditor/index.md
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/TiptapEditor.vue
Labels: size/XL

#470 fix: update vuetify-pro-tiptap dependency URL in package.json
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/S

#472 refactor: update VXBreadcrumbs component styling
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Breadcrumbs/VXBreadcrumbs.vue
Labels: size/XS

#473 fix: update funnel chart data values and add new data entry
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChart/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/presets.config.ts
Labels: size/S
