Repository qor5/x, pull requests merged in 2025-02, with the labels that each got.

#413 Fix daniel tiptap
  ui/vuetifyx/tiptap-editor.go
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/TiptapEditor/index.md
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/Extensions/CallbackActionButton.vue
  ui/vuetifyx/vuetifyxjs/src/lib/TiptapEditor/TiptapEditor.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/tiptap.ts
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
  ui/vuetifyx/vuetifyxjs/tsconfig.json
  ui/vuetifyx/vuetifyxjs/update-tip-tap.sh
Labels: size/XL

#418 fix: update dependency versions and clean up configuration files
  .github/workflows/vuetifyjs-build.yml
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/patches/@vitepress-code-preview__container.patch
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXBtn.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
Labels: size/XXL

#416 [Snyk] Upgrade @mdi/font from 7.0.96 to 7.4.47
  ui/vuetifyx/vuetifyxjs/dist/assets/materialdesignicons-webfont.eot
  ui/vuetifyx/vuetifyxjs/dist/assets/materialdesignicons-webfont.ttf
  ui/vuetifyx/vuetifyxjs/dist/assets/materialdesignicons-webfont.woff
  ui/vuetifyx/vuetifyxjs/dist/assets/materialdesignicons-webfont.woff2
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/S

#419 fix: update pnpm version to 9.14.4 in CI workflows
  .github/workflows/doc-build.yml
  .github/workflows/vuetifyjs-test.yml
Labels: size/XS

#423 Feat vxselect item
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
Labels: needs-rebase, size/L

#420 WIP: feat: enhance VXSelect component with slot support for custom item rendering
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXSelect/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSelect.vue
Labels: size/L, do-not-merge/work-in-progress
