Repository qor5/x, pull requests merged in 2025-01, with the labels that each got.

#404 Feat iframe email2
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDialog/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Common/VXDialog.vue
  ui/vuetifyx/vx-dialog.go
Labels: needs-rebase, size/L

#405 Fix remove height
  ui/vuetifyx/scroll-iframe.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/L

#407 feat: add vx-breadcrumbs
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXBreadcrumbs/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXTreeview/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/Breadcrumbs/VXBreadcrumbs.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-breadcrumbs.go
Labels: needs-rebase, size/XXL

#415 fix container overflow iframe
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/M
