Repository qor5/x, pull requests merged in 2025-04, with the labels that each got.

#446 feat: add VXModelProxy component and update sidebar links for VXTabs
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXModelConverter/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXModelProxy/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/VXModelProxy.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-model-proxy.go
Labels: size/L

#443 WIP: Feat daniel timepicker
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXDatePicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXRangePicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXTabs/index.md
  ui/vuetifyx/vuetifyxjs/docs/Components/VXTimepicker/index.md
  ui/vuetifyx/vuetifyxjs/docs/sidebar.ts
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePickerBase.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Tabs/VXTabs.vue
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/index.ts
  ui/vuetifyx/vx-tabs.go
  ui/vuetifyx/vx-time-picker.go
Labels: do-not-merge/work-in-progress, size/XXL

#445 style: update cursor styles for date picker components
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimeSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/_vuetify.scss
Labels: size/S

#448 refactor: enhance VXTabs component structure and styling
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Tabs/VXTabs.vue
Labels: size/L

#449 style: update Vuetifyx CSS and SCSS for improved tab styling
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_Detailing.scss
Labels: size/XS

#451 WIP: fix: improve number input handling in VXField component
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXField.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useBindingValue.ts
Labels: size/M, do-not-merge/work-in-progress

#454 feat: add FunnelChart component and integrate with VXChart
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChart/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/FunnelChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/VXChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/presets.config.ts
Labels: size/XXL

#456 Wrap slot in a div in VXModelProxy component for improved structure
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/VXModelProxy.vue
Labels: size/XS

#457 Enhance ConditionSwitch component styling
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXSegmentForm/ConditionSwitch.vue
Labels: size/XS

#458 Update VXField component to support various input types and enhance useBindingValue functionality
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useBindingValue.ts
Labels: size/S

#459 Fix ScrollIframe component to prevent errors when iframe is not present
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/XS
