Repository qor5/x, pull requests merged in 2025-06, with the labels that each got.

#475 Fix iframe event
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/ScrollIframe.vue
Labels: size/S

#479 chore: update GitHub Actions workflows and package dependencies
  .github/workflows/doc-build.yml
  .github/workflows/go.yml
  .github/workflows/vuetifyjs-build.yml
  .github/workflows/vuetifyjs-test.yml
  go.mod
  go.sum
  ui/redactor/redactorjs/package.json
  ui/redactor/redactorjs/pnpm-lock.yaml
  ui/tiptap/tiptapjs/package.json
  ui/tiptap/tiptapjs/pnpm-lock.yaml
Labels: size/L

#482 fix: improve datetime parsing in FilterData based on ItemType
  ui/vuetifyx/filter.go
Labels: size/XS

#483 feat: enhance MessageListener component with global message handling
  ui/vuetifyx/message-listener.go
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/MessageListener.vue
Labels: size/M

#484 Fix-datepicker-bug
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXField/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/RangePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimeSelect.vue
  ui/vuetifyx/vuetifyxjs/src/lib/composables/useDatePicker.ts
  ui/vuetifyx/vuetifyxjs/src/lib/utils/dateParser.test.ts
  ui/vuetifyx/vuetifyxjs/src/lib/utils/dateParser.ts
  ui/vuetifyx/vuetifyxjs/src/lib/utils/index.ts
Labels: size/XL

#486 fix: update VXChart component and CSS styles
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/docs/Components/VXChart/index.md
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/FunnelChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/VXChart.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Chart/presets.config.ts
  ui/vuetifyx/vx-chart.go
Labels: needs-rebase, size/XL

#485 feat: align media box button to the left in PageBuilder
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/DatePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/Form/VXDatePicker/TimePicker.vue
  ui/vuetifyx/vuetifyxjs/src/lib/scss/page/_PageBuilder.scss
Labels: size/S
