Repository qor5/x, pull requests merged in 2025-09, with the labels that each got.

#502 Add gRPC connection factory with load balancing
  errornotifierx/airbrake.go
  errornotifierx/config_test.go
  errornotifierx/errornotifier.go
  errornotifierx/slog.go
  go.mod
  go.sum
  gormx/database.go
  gormx/tracing.go
  grpcx/bufconn.go
  grpcx/config.go
  grpcx/conn.go
  grpcx/logger.go
  grpcx/logging.go
  grpcx/server.go
  healthz/grpc_test.go
  httpx/server.go
  netx/dial.go
  normalize/grpc.go
  slogx/slog.go
  statusx/buf.gen.yaml
  statusx/buf.yaml
  statusx/gen/testdata/v1/input.pb.go
  statusx/gen/testdata/v1/input.pb.validate.go
  statusx/http.go
  statusx/testdata/proto/testdata/v1/input.proto
  statusx/validate_test.go
  statusx/vproto.go
Labels: size/XL

#504 Add Connect mux with VProto error handling and improve error hooks
  connectx/mux.go
  gormx/database.go
  normalize/grpc.go
  statusx/http.go
  statusx/vproto.go
Labels: size/L

#505 Refactor Notify method in LogNotifier to improve context handling
  errornotifierx/slog.go
Labels: size/S

#507 Add gobusx package for bus setup and migration
  go.mod
  go.sum
  gobusx/bus.go
  gobusx/migrate.go
  grpcx/bufconn.go
  grpcx/conn.go
  httpx/config.go
  i18nx/embed/default.csv
  i18nx/i18n_test.go
Labels: size/L

#515 Update Tiptap and Vuetify dependencies to version 2.24.0, add Vue Rou…
  .github/workflows/vuetifyjs-build.yml
  .github/workflows/vuetifyjs-test.yml
  ui/tiptap/tiptapjs/dist/tiptapjs.umd.cjs
  ui/tiptap/tiptapjs/package.json
  ui/tiptap/tiptapjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/components.d.ts
  ui/vuetifyx/vuetifyxjs/dist/assets/vuetifyx.min.css
  ui/vuetifyx/vuetifyxjs/dist/vuetifyx.min.js
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
  ui/vuetifyx/vuetifyxjs/src/lib/plugins/tiptap.ts
Labels: size/XXL

#521 fix: dependbot issues
  ui/cropper/cropperjs/package.json
  ui/cropper/cropperjs/pnpm-lock.yaml
  ui/redactor/redactorjs/package.json
  ui/redactor/redactorjs/pnpm-lock.yaml
  ui/tiptap/build.sh
  ui/tiptap/tiptapjs/.gitignore
  ui/tiptap/tiptapjs/README.md
  ui/tiptap/tiptapjs/index.html
  ui/tiptap/tiptapjs/package.json
  ui/tiptap/tiptapjs/pnpm-lock.yaml
  ui/tiptap/tiptapjs/public/favicon.ico
  ui/tiptap/tiptapjs/src/demo/App.vue
  ui/tiptap/tiptapjs/src/demo/components/EditorExample.vue
  ui/tiptap/tiptapjs/src/demo/main.ts
  ui/tiptap/tiptapjs/src/demo/vite-env.d.ts
  ui/tiptap/tiptapjs/src/lib/Editor.vue
  ui/tiptap/tiptapjs/src/lib/Icon.vue
  ui/tiptap/tiptapjs/src/lib/icons/add_col_after.svg
  ui/tiptap/tiptapjs/src/lib/icons/add_col_before.svg
  ui/tiptap/tiptapjs/src/lib/icons/add_row_after.svg
  ui/tiptap/tiptapjs/src/lib/icons/add_row_before.svg
  ui/tiptap/tiptapjs/src/lib/icons/bold.svg
  ui/tiptap/tiptapjs/src/lib/icons/checklist.svg
  ui/tiptap/tiptapjs/src/lib/icons/code.svg
  ui/tiptap/tiptapjs/src/lib/icons/code_block.svg
  ui/tiptap/tiptapjs/src/lib/icons/combine_cells.svg
  ui/tiptap/tiptapjs/src/lib/icons/delete_col.svg
  ui/tiptap/tiptapjs/src/lib/icons/delete_row.svg
  ui/tiptap/tiptapjs/src/lib/icons/delete_table.svg
  ui/tiptap/tiptapjs/src/lib/icons/github.svg
  ui/tiptap/tiptapjs/src/lib/icons/hr.svg
  ui/tiptap/tiptapjs/src/lib/icons/image.svg
  ui/tiptap/tiptapjs/src/lib/icons/italic.svg
  ui/tiptap/tiptapjs/src/lib/icons/link.svg
  ui/tiptap/tiptapjs/src/lib/icons/mention.svg
  ui/tiptap/tiptapjs/src/lib/icons/ol.svg
  ui/tiptap/tiptapjs/src/lib/icons/paragraph.svg
  ui/tiptap/tiptapjs/src/lib/icons/quote.svg
  ui/tiptap/tiptapjs/src/lib/icons/redo.svg
  ui/tiptap/tiptapjs/src/lib/icons/remove.svg
  ui/tiptap/tiptapjs/src/lib/icons/strike.svg
  ui/tiptap/tiptapjs/src/lib/icons/table.svg
  ui/tiptap/tiptapjs/src/lib/icons/ul.svg
  ui/tiptap/tiptapjs/src/lib/icons/underline.svg
  ui/tiptap/tiptapjs/src/lib/icons/undo.svg
  ui/tiptap/tiptapjs/src/lib/main.ts
  ui/tiptap/tiptapjs/src/lib/sass/editor.scss
  ui/tiptap/tiptapjs/src/lib/sass/main.scss
  ui/tiptap/tiptapjs/src/lib/sass/menubar.scss
  ui/tiptap/tiptapjs/src/lib/sass/menububble.scss
  ui/tiptap/tiptapjs/src/lib/sass/variables.scss
  ui/tiptap/tiptapjs/src/lib/vite-env.d.ts
  ui/tiptap/tiptapjs/tsconfig.app.json
  ui/tiptap/tiptapjs/tsconfig.json
  ui/tiptap/tiptapjs/tsconfig.node.json
  ui/tiptap/tiptapjs/vite.config.ts
  ui/vuetifyx/vuetifyxjs/package.json
  ui/vuetifyx/vuetifyxjs/pnpm-lock.yaml
Labels: size/XXL

#511 gormx testhelper && statusx refactor to support field violation
  errornotifierx/example/example.yaml
  go.mod
  gormx/container.go
  gormx/database.go
  gormx/embed/default-database-config.yaml
  gormx/gorm_test.go
  gormx/omit_associations_test.go
  gormx/postgresx/postgres_test.go
  gormx/testhelper.go
  grpcx/config.go
  grpcx/example/client.yaml
  grpcx/example/server.yaml
  grpcx/server.go
  i18nx/i18n.go
  jsonx/json.go
  jsonx/json_test.go
  jsonx/map.go
  jsonx/map_test.go
  jsonx/type.go
  normalize/connect.go
  normalize/grpc.go
  normalize/normalize.go
  ratelimiterx/grpc_test.go
  ratelimiterx/ratelimit.go
  s3x/example/example.yaml
  s3x/s3.go
  statusx/buf.gen.yaml
  statusx/buf.lock
  statusx/buf.yaml
  statusx/code.go
  statusx/code_test.go
  statusx/connect.go
  statusx/details.go
  statusx/field.go
  statusx/field_test.go
  statusx/gen/status/v1/localized.pb.go
  statusx/gen/status/v1/localized.pb.validate.go
  statusx/grpc.go
  statusx/http.go
  statusx/interceptor.go
  statusx/interceptor_test.go
  statusx/proto/status/v1/localized.proto
  statusx/status.go
  statusx/status_test.go
  statusx/testhelper.go
  statusx/testhelper_test.go
  statusx/translate.go
  statusx/translate_test.go
  statusx/validate.go
  statusx/validate_test.go
  statusx/vproto.go
Labels: size/XXL
